echo -e "\e[31mred colour\e[0m"
echo -e "\e[32mgreen colour\e[0m"
echo -e "\e[33myellow colour\e[0m"
echo -e "\e[34mblue colour\e[0m"
echo -e "\e[35mmagenta colour\e[0m"
echo -e "\e[36mcyan colour\e[0m"
